/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ee_ut_f2f_gatherer_parameters_WinDllInformation */

#ifndef _Included_ee_ut_f2f_gatherer_parameters_WinDllInformation
#define _Included_ee_ut_f2f_gatherer_parameters_WinDllInformation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ee_ut_f2f_gatherer_parameters_WinDllInformation
 * Method:    findWinData
 * Signature: (Lee/ut/f2f/gatherer/model/WindowsAttributes;)Lee/ut/f2f/gatherer/model/WindowsAttributes;
 */
JNIEXPORT jobject JNICALL Java_ee_ut_f2f_gatherer_parameters_WinDllInformation_findWinData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
