/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ee_ut_f2f_gatherer_parameters_LinuxSoInformation */

#ifndef _Included_ee_ut_f2f_gatherer_parameters_LinuxSoInformation
#define _Included_ee_ut_f2f_gatherer_parameters_LinuxSoInformation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ee_ut_f2f_gatherer_parameters_LinuxSoInformation
 * Method:    findData
 * Signature: (Lee/ut/f2f/gatherer/model/LinuxAttributes;)Lee/ut/f2f/gatherer/model/LinuxAttributes;
 */
JNIEXPORT jobject JNICALL Java_ee_ut_f2f_gatherer_parameters_LinuxSoInformation_findData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
